## <span style="color:green">(possible) Solutions</span>

In [2]:
import numpy as np

In [3]:
# 1. Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.
# Subsequently create a 3x10 array from them.
# Ultimately compute the sum column-wise (over axis 0).
x_0 = np.zeros(10)
x_1 = np.ones(10)
x_5 = x_1*5

combined = np.array([x_0,x_1,x_5])
print(combined.shape)
print(combined)
sum_column = combined.sum(axis=0)
sum_column

(3, 10)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [4]:
# 2. Create an array of length N=12 equally spaced between -5 and (including) 3, 
# then compute the square of these values. 

y_array = np.linspace(-5,3,12)
y_square = y_array**2
y_square

array([2.50000000e+01, 1.82561983e+01, 1.25702479e+01, 7.94214876e+00,
       4.37190083e+00, 1.85950413e+00, 4.04958678e-01, 8.26446281e-03,
       6.69421488e-01, 2.38842975e+00, 5.16528926e+00, 9.00000000e+00])

In [5]:
# 3. Create a 2D grid of longitudes lambda [0,360] deg and latitudes phi [-90,90] every 30 degrees.

d_deg = 30 # stepsize
lon = np.arange(0,361,d_deg)
lat = np.arange(-90,91,d_deg)

LAT,LON=np.meshgrid(lat,lon)

# Then calculate sin(30) and cos(pi), i.e. find out how to use degrees and radians with numpy functions.
print(np.sin(30))              # this is wrong
print(np.sin(np.deg2rad(30)))  # this is correct
print(np.sin(30*np.pi/180))              # this is also correct
# --> numpy trigonometric functions want radians, not degrees
print(np.cos(np.pi))


-0.9880316240928618
0.49999999999999994
0.49999999999999994
-1.0


In [6]:
# 4. Create an array of `N=[500,1200,1e5]` samples of the Normal
# distribution of mean=3, standard deviation=2.
# Determine the mean and standard deviation with numpy functions.

for N in [500,1200,int(1e5)]:
    D = np.random.normal(loc=3, scale=2, size=N)
    print(f'N = {N:6d}, mean = {D.mean():.2f}, std = {D.std()}')
    
# again, the numbers and letters after the colon in the f-string 
# determine the output format

N =    500, mean = 2.97, std = 2.066846997752929
N =   1200, mean = 2.95, std = 2.053970086844161
N = 100000, mean = 3.00, std = 1.9934882836124663


In [7]:
#5. _Hard:_ Compute an approximation to $\pi$ using Monte Carlo sampling. Use only the `numpy.random.uniform()` function. These hints may help:
# - The area of a circle is $area = \pi \times radius^2$
# - Sample the unit square $(0,1)\times(0,1)$ with $N$ uniformly in $x$ and $y$ distributed points.

def pi_estimation(sample_size=10000):
    #estimating pi using monte carlo sampling
    a = np.random.random(sample_size)
    b = np.random.random(sample_size)
    a = np.power(a, 2)
    b = np.power(b, 2)
    a = np.add(a, b)
    N = np.sum(a < 1)
    print("pi equals", 4.0 * N / sample_size)

pi_estimation(10000000)


pi equals 3.141784
